# Generated by Django 5.2.1 on 2025-11-01 13:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionUnitClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Action Unit Class',
                'verbose_name_plural': 'Action Unit Classes',
                'db_table': 'action_unit_classes',
            },
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('denomination', models.CharField(default='Seventh-day Adventist', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Church',
                'verbose_name_plural': 'Churches',
                'db_table': 'churches',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superintendent', 'Superintendent'), ('teacher', 'Teacher'), ('member', 'Member'), ('system_admin', 'System Administrator')], default='system_admin', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_officer', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='actionunit.church')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1-Q2', 'Quarter 1 & 2 (Jan-Jun)'), ('Q3-Q4', 'Quarter 3 & 4 (Jul-Dec)')], max_length=10)),
                ('year', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_unit_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_orders', to='actionunit.actionunitclass')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Order',
                'verbose_name_plural': 'Book Orders',
                'db_table': 'book_orders',
                'ordering': ['-year', '-quarter', '-created_at'],
                'unique_together': {('action_unit_class', 'quarter', 'year')},
            },
        ),
        migrations.AddField(
            model_name='actionunitclass',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='actionunit.church'),
        ),
        migrations.CreateModel(
            name='ClassMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action_unit_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='actionunit.actionunitclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Member',
                'verbose_name_plural': 'Class Members',
                'db_table': 'class_members',
                'unique_together': {('action_unit_class', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('GHS', 'Ghana Cedi'), ('USD', 'US Dollar')], default='GHS', max_length=3)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_unit_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='actionunit.actionunitclass')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_offerings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offering',
                'verbose_name_plural': 'Offerings',
                'db_table': 'offerings',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('GHS', 'Ghana Cedi'), ('USD', 'US Dollar')], default='GHS', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_books', to='actionunit.church')),
            ],
            options={
                'verbose_name': 'Quarterly Book',
                'verbose_name_plural': 'Quarterly Books',
                'db_table': 'quarterly_books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free_trial', 'Free Trial'), ('monthly', 'Monthly'), ('quarterly', ' Quarterly'), ('annual', 'Annual')], default='free_trial', max_length=20)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], default='trialing', max_length=20)),
                ('trial_end_date', models.DateField()),
                ('current_period_end', models.DateField()),
                ('grace_period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='actionunit.church')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='actionunitclass',
            unique_together={('church', 'name')},
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=True)),
                ('absence_reason', models.CharField(blank=True, choices=[('sick', 'Sick'), ('traveling', 'Traveling'), ('work', 'Work'), ('family_emergency', 'Family Emergency'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=100, null=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('class_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='actionunit.classmember')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendances',
                'unique_together': {('class_member', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action_unit_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='actionunit.actionunitclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Teacher',
                'verbose_name_plural': 'Class Teachers',
                'db_table': 'class_teachers',
                'unique_together': {('action_unit_class', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('book_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='actionunit.bookorder')),
                ('quarterly_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='actionunit.quarterlybook')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
                'unique_together': {('book_order', 'quarterly_book')},
            },
        ),
    ]
