# Generated by Django 5.2.1 on 2025-10-16 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionunit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionUnitClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='actionunit.church')),
            ],
            options={
                'verbose_name': 'Action Unit Class',
                'verbose_name_plural': 'Action Unit Classes',
                'db_table': 'action_unit_classes',
                'unique_together': {('church', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action_unit_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignment', to='actionunit.actionunitclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Teacher',
                'verbose_name_plural': 'Class Teachers',
                'db_table': 'class_teachers',
            },
        ),
        migrations.CreateModel(
            name='ClassMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action_unit_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='actionunit.actionunitclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Member',
                'verbose_name_plural': 'Class Members',
                'db_table': 'class_members',
                'unique_together': {('action_unit_class', 'user')},
            },
        ),
    ]
