# Generated by Django 5.2.1 on 2025-10-16 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionunit', '0002_actionunitclass_classteacher_classmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacher',
            name='action_unit_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='actionunit.actionunitclass'),
        ),
        migrations.AlterField(
            model_name='classteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='classteacher',
            unique_together={('action_unit_class', 'teacher')},
        ),
    ]
