# Generated by Django 5.2.1 on 2025-10-16 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionunit', '0003_alter_classteacher_action_unit_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
