# Generated by Django 5.2.1 on 2025-10-17 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionunit', '0004_alter_classteacher_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=True)),
                ('absence_reason', models.CharField(blank=True, choices=[('sick', 'Sick'), ('traveling', 'Traveling'), ('work', 'Work'), ('family_emergency', 'Family Emergency'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=100, null=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('class_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='actionunit.classmember')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendances',
                'unique_together': {('class_member', 'date')},
            },
        ),
    ]
