# Generated by Django 5.2.1 on 2025-10-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionunit', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmember',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
