# Generated by Django 5.2.1 on 2025-10-17 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionunit', '0006_classmember_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('GHS', 'Ghana Cedi'), ('USD', 'US Dollar')], default='GHS', max_length=3)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_unit_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='actionunit.actionunitclass')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_offerings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offering',
                'verbose_name_plural': 'Offerings',
                'db_table': 'offerings',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
