# Generated by Django 5.2.1 on 2025-10-19 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionunit', '0007_offering'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('GHS', 'Ghana Cedi'), ('USD', 'US Dollar')], default='GHS', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_books', to='actionunit.church')),
            ],
            options={
                'verbose_name': 'Quarterly Book',
                'verbose_name_plural': 'Quarterly Books',
                'db_table': 'quarterly_books',
                'ordering': ['-created_at'],
            },
        ),
    ]
