# Generated by Django 5.2.1 on 2025-10-19 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionunit', '0008_quarterlybook'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1-Q2', 'Quarter 1 & 2 (Jan-Jun)'), ('Q3-Q4', 'Quarter 3 & 4 (Jul-Dec)')], max_length=10)),
                ('year', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_unit_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_orders', to='actionunit.actionunitclass')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Order',
                'verbose_name_plural': 'Book Orders',
                'db_table': 'book_orders',
                'ordering': ['-year', '-quarter', '-created_at'],
                'unique_together': {('action_unit_class', 'quarter', 'year')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('book_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='actionunit.bookorder')),
                ('quarterly_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='actionunit.quarterlybook')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
                'unique_together': {('book_order', 'quarterly_book')},
            },
        ),
    ]
