# Generated by Django 5.2.1 on 2025-10-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionunit', '0009_bookorder_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_officer',
            field=models.BooleanField(default=False),
        ),
    ]
